export async function cartLoader(){
    return [
        {
          id: 1,
          name: "Chaussettes motif tropical",
          price: 20,
          model: "mi chaussettes",
          brand: "KINDY",
          count: 1,
          stock: 20,
          size: "L",
          color: "",
          motif : "tropical",
          img: "https://www.chaussettes.com/14186-large_default/mi-chaussettes-en-coton-motif-tropical-made-in-france.jpg",
        },
        {
          id: 2,
          name: "Chaussettes motif tropical",
          price: 15,
          model: "mi chaussettes",
          brand: "KINDY",
          count: 2,
          stock: 3,
          size: "L",
          color: "",
          motif : "tropical",
          img: "https://www.chaussettes.com/14186-large_default/mi-chaussettes-en-coton-motif-tropical-made-in-france.jpg",
        },
        {
          id: 3,
          name: "Chaussettes motif tropical",
          price: 20,
          model: "mi chaussettes",
          brand: "KINDY",
          count: 5,
          stock: 20,
          size: "L",
          color: "",
          motif : "tropical",
          img: "https://www.chaussettes.com/14186-large_default/mi-chaussettes-en-coton-motif-tropical-made-in-france.jpg",
        },
        {
          id: 4,
          name: "Chaussettes motif tropical",
          price: 8.99,
          model: "mi chaussettes",
          brand: "KINDY",
          count: 1,
          stock: 5,
          size: "L",
          color: "",
          motif : "tropical",
          img: "https://www.chaussettes.com/14186-large_default/mi-chaussettes-en-coton-motif-tropical-made-in-france.jpg",
        },
        {
          id: 5,
          name: "Chaussettes motif tropical",
          price: 20,
          model: "mi chaussettes",
          brand: "KINDY",
          count: 1,
          stock: 30,
          size: "L",
          color: "",
          motif : "tropical",
          img: "https://www.chaussettes.com/14186-large_default/mi-chaussettes-en-coton-motif-tropical-made-in-france.jpg",
        },
        {
          id: 6,
          name: "Chaussettes motif tropical",
          price: 5.62,
          model: "mi chaussettes",
          brand: "KINDY",
          count: 5,
          stock: 10,
          size: "L",
          color: "",
          motif : "tropical",
          img: "https://www.chaussettes.com/14186-large_default/mi-chaussettes-en-coton-motif-tropical-made-in-france.jpg",
        },
      ];
}